### ISSUE TITLE
Learn to use git-hubs fork features properly

### ISSUE THREAD

**Issue by SOELexicon** [BurstNation/Burst-Core-Wallet#7]
for change tracking and various other benefits. please refrain from doing direct commits to the repo.

Fork it.. as it makes it easier long term. as to rollback a change we need to step through 4 commits where all that changed is the names of class's instead where we could of just reverted 1 merge.

this keeps the tree tidier and doesn't take any longer to do

without going into much detail this is one of the benefits from using the fork feature as a collaboration tool. and if were going to use git-hub as a team we might as well use it properly.

**Comment by IceBurst** [comment]
OVER RATED
